### ISSUE TITLE
Isn't this supposed to be Body instead of String?

### ISSUE THREAD

**Issue by l1x** [robertohuertasm/aws-rust#1]
Hi,

I am trying to understand your code but I am not sure about this. Is this supposed to be String or Body?

https://github.com/robertohuertasm/aws-lambda-rust/blob/341d287c6ef5ae43001708f9b1ec22a5a1702a68/src/main.rs#L18

**Comment by l1x** [comment]
Nevermind, I just figured it out.

**Comment by robertohuertasm** [comment]
Sorry for the delay in the answer. I see you've figured it out. If I'm not mistaken I remember the body came as a string so the deserialization has to be manual (ln. 92). Thanks for asking though!

**Comment by l1x** [comment]
Thank you! Absolutely, I just thought we need to serialise into Body straight up, but you do that later.
